services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: leronbaton/counter:v4.0.0
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_URL=redis://storage
    depends_on:
      - storage
    healthcheck:
      test: "exit 0"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: "exit 0"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  library:
    image: leronbaton/library:v3.0.0
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - COUNTER_URL=counter
      - MONGODB_URL=mongodb://root:example@mongo:27017
    depends_on:
      counter:
        condition:
          service_healthy
      mongo:
        condition: 
          service_healthy